#!/usr/bin/env python3
"""Derive the TENDRIL CLI masthead from the high-res ANSI master (build-time only).

Pipeline (deterministic, no hand-drawn glyphs):

  1. extract   TENDRIL_LOGO.ans (200x56 cells of truecolor half-blocks = a
               200x112 square-pixel raster) -> per-pixel lime coverage,
               cropped to the logo's bounding box -> master_coverage.txt.
               Only this step needs the 317 KB master; everything after runs
               from the committed coverage file.
  2. segment   split the raster into elements at empty columns:
               icon, T, E, N, D, R, I, L.
  3. fit       grid-fit like font hinting. Wordmark: strong horizontal
               edges (bar tops/bottoms) snap to quadrant rows, each letter's
               stem edges snap to quadrant columns, sub-resolution modular
               seams collapse; the master is sampled through that monotone
               warp, so diagonals stay diagonals. Icon: symmetrized about its
               spine, every master stroke fitted separately (own sub-quadrant
               phase, area-preserving threshold) and never allowed to touch
               another stroke, so the negative spaces survive; the spine is
               exactly one cell wide and stays segmented.
  4. sample    exact box-filter coverage per quadrant (2x2 per cell) ->
               Unicode quadrant primitive per cell.
  5. emit      tendril_full.ans / tendril_compact.ans: truecolor fg-only SGR,
               transparent background, reset closing every run.

Usage:
  build_masthead.py --extract [MASTER.ans]   refresh master_coverage.txt
  build_masthead.py                          build + verify all tiers
  build_masthead.py --embed                  ... and print the runtime block
"""
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
COVERAGE = os.path.join(HERE, "master_coverage.txt")
DEFAULT_MASTER = os.path.expanduser("~/Downloads/TENDRIL_LOGO.ans")

LIME = (203, 253, 117)          # the CLI's own C_LIME
LEVELS = 15                     # coverage quantization in master_coverage.txt

# quadrant bits: TL=1 TR=2 BL=4 BR=8
GLYPH = {0: " ", 1: "▘", 2: "▝", 3: "▀", 4: "▖", 5: "▌", 7: "▛",
         8: "▗", 10: "▐", 11: "▜", 12: "▄", 13: "▙", 14: "▟", 15: "█"}
# the two diagonals have no single-glyph form; keep the stronger quadrant
DIAGONAL = {6: (2, 4), 9: (1, 8)}

ELEMENT_NAMES = ["icon", "T", "E", "N", "D", "D", "R", "I", "L"]  # D = stem + bowl


# ---------------------------------------------------------------- 1. extract

def parse_master(text):
    """Half-block ANSI -> square-pixel RGB raster (list of rows)."""
    tok = re.compile(r"\x1b\[([0-9;]*)m|\n|[^\x1b\n]")
    fg = bg = (0, 0, 0)
    rows, row = [], []
    for m in tok.finditer(text):
        t = m.group(0)
        if m.group(1) is not None or t.startswith("\x1b"):
            p = [int(v) if v else 0 for v in (m.group(1) or "0").split(";")]
            i = 0
            while i < len(p):
                if p[i] == 0:
                    fg = bg = (0, 0, 0)
                elif p[i] in (38, 48) and i + 4 < len(p) and p[i + 1] == 2:
                    c = tuple(p[i + 2:i + 5])
                    fg, bg = (c, bg) if p[i] == 38 else (fg, c)
                    i += 4
                i += 1
        elif t == "\n":
            rows.append(row)
            row = []
        else:
            row.append({"▀": (fg, bg), "▄": (bg, fg), "█": (fg, fg)}.get(t, (bg, bg)))
    if row:
        rows.append(row)
    px = []
    for r in rows:
        px.append([c[0] for c in r])
        px.append([c[1] for c in r])
    return px


def lum(c):
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def extract(master_path):
    with open(master_path, "rb") as f:
        raw = f.read()
    px = parse_master(raw.decode())
    lums = sorted(lum(c) for r in px for c in r)
    dark = lums[len(lums) // 10]                       # background level
    face = lums[-len(lums) // 200]                     # lime face level
    alpha = [[min(1.0, max(0.0, (lum(c) - dark) / (face - dark))) for c in r] for r in px]
    ys = [y for y, r in enumerate(alpha) if max(r) > 0.05]
    xs = [x for x in range(len(alpha[0])) if max(r[x] for r in alpha) > 0.05]
    y0, y1, x0, x1 = min(ys), max(ys), min(xs), max(xs)
    with open(COVERAGE, "w") as f:
        f.write(f"# TENDRIL masthead master coverage (generated by build_masthead.py --extract)\n")
        f.write(f"# source {os.path.basename(master_path)} sha256 "
                f"{hashlib.sha256(raw).hexdigest()} {len(raw)} bytes\n")
        f.write(f"# raster {len(px[0])}x{len(px)} px (half-block cells), "
                f"crop x{x0}-{x1} y{y0}-{y1}, lime coverage 0-{LEVELS:x} per px\n")
        for y in range(y0, y1 + 1):
            f.write("".join(f"{round(alpha[y][x] * LEVELS):x}" for x in range(x0, x1 + 1)) + "\n")
    print(f"wrote {COVERAGE}: {x1 - x0 + 1}x{y1 - y0 + 1} px")


def load_coverage():
    with open(COVERAGE) as f:
        rows = [ln.strip() for ln in f if ln.strip() and not ln.startswith("#")]
    return [[int(ch, 16) / LEVELS for ch in r] for r in rows]


# ---------------------------------------------------------------- 2. segment

def segment(cov):
    h, w = len(cov), len(cov[0])
    ink_col = [any(cov[y][x] >= 0.5 for y in range(h)) for x in range(w)]
    runs, start = [], None
    for x in range(w + 1):
        on = x < w and ink_col[x]
        if on and start is None:
            start = x
        if not on and start is not None:
            runs.append((start, x - 1))
            start = None
    assert len(runs) == len(ELEMENT_NAMES), f"expected {len(ELEMENT_NAMES)} runs, got {runs}"
    elements = []
    for name, (a, b) in zip(ELEMENT_NAMES, runs):
        if elements and elements[-1][0] == name:
            elements[-1] = (name, elements[-1][1], b)
        else:
            elements.append((name, a, b))
    return elements


def element_field(cov, a, b, close_seams):
    """Coverage of one element (columns a..b). Letters get their 1-px modular
    seams closed: they sit below quadrant resolution and would otherwise
    alias into random notches."""
    f = [row[a:b + 1] for row in cov]
    if not close_seams:
        return f
    h, w = len(f), len(f[0])
    g = [r[:] for r in f]
    for y in range(h):
        for x in range(w):
            if f[y][x] >= 0.5:
                continue
            vert = 0 < y < h - 1 and f[y - 1][x] >= 0.5 and f[y + 1][x] >= 0.5
            horz = 0 < x < w - 1 and f[y][x - 1] >= 0.5 and f[y][x + 1] >= 0.5
            if vert or horz:
                g[y][x] = 1.0
    return g


# ---------------------------------------------------------------- 3/4. sample

def box(f, x0, x1, y0, y1):
    """Exact area-weighted mean of field f over [x0,x1) x [y0,y1) (outside = 0)."""
    h, w = len(f), len(f[0])
    total = 0.0
    for y in range(max(0, int(y0)), min(h, int(y1) + 1)):
        wy = min(y + 1, y1) - max(y, y0)
        if wy <= 0:
            continue
        row = f[y]
        for x in range(max(0, int(x0)), min(w, int(x1) + 1)):
            wx = min(x + 1, x1) - max(x, x0)
            if wx > 0:
                total += row[x] * wx * wy
    return total / ((x1 - x0) * (y1 - y0))


def edge_strength(f, axis):
    """strength[b] = how many rows (axis='x') / columns (axis='y') change
    ink state across boundary b. Straight stems and bars give strong peaks;
    diagonals spread out and stay weak."""
    h, w = len(f), len(f[0])
    ink = [[v >= 0.5 for v in r] for r in f]
    if axis == "x":
        return [sum(ink[y][b - 1] != ink[y][b] for y in range(h)) if 0 < b < w else
                sum(ink[y][0 if b == 0 else w - 1] for y in range(h)) for b in range(w + 1)]
    return [sum(ink[b - 1][x] != ink[b][x] for x in range(w)) if 0 < b < h else
            sum(ink[0 if b == 0 else h - 1][x] for x in range(w)) for b in range(h + 1)]


def snap_edges(strength, lo, hi, n, min_feature=3, rel=0.3):
    """Grid-fit: map strong edges in [lo, hi] (px boundaries) to integer
    quadrant boundaries 0..n, monotone, keeping every feature >= min_feature px
    at >= 1 quadrant, minimizing squared displacement. Returns control points."""
    peak = max(strength[lo:hi + 1]) or 1
    edges = [lo] + [b for b in range(lo + 1, hi) if strength[b] >= rel * peak] + [hi]
    t = [(b - lo) * n / (hi - lo) for b in edges]
    m = len(edges)
    INF = float("inf")
    cost = [[INF] * (n + 1) for _ in range(m)]
    back = [[0] * (n + 1) for _ in range(m)]
    cost[0][0] = 0.0
    for k in range(1, m):
        need = 1 if edges[k] - edges[k - 1] >= min_feature else 0
        for q in range(n + 1):
            if k == m - 1 and q != n:
                continue
            c = (q - t[k]) ** 2
            for p in range(0, q - need + 1):
                if cost[k - 1][p] + c < cost[k][q]:
                    cost[k][q] = cost[k - 1][p] + c
                    back[k][q] = p
    qs = [n]
    for k in range(m - 1, 0, -1):
        qs.append(back[k][qs[-1]])
    return list(zip(edges, qs[::-1]))


def bounds_from(points, n):
    """Inverse of the piecewise-linear px->quadrant map: px position of every
    quadrant boundary 0..n. Collapsed spans (sub-resolution seams) are split
    down the middle so they fade out instead of snapping to one side."""
    out = []
    for j in range(n + 1):
        same = [b for b, q in points if q == j]
        if same:
            out.append((min(same) + max(same)) / 2)
            continue
        for (b0, q0), (b1, q1) in zip(points, points[1:]):
            if q0 < j < q1:
                out.append(b0 + (j - q0) * (b1 - b0) / (q1 - q0))
                break
    return out


def sample_bounds(f, xb, yb, thresh=0.5):
    return [[1 if box(f, xb[i], xb[i + 1], yb[j], yb[j + 1]) >= thresh else 0
             for i in range(len(xb) - 1)] for j in range(len(yb) - 1)]


def fit_letter(f, sx, yb):
    """Grid-fitted letter: its stems' vertical edges snap to quadrant columns
    (shared bars already snapped to rows via `yb`)."""
    w = len(f[0])
    n = max(1, round(w / sx))
    pts = snap_edges(edge_strength(f, "x"), 0, w, n, min_feature=3)
    q = sample_bounds(f, bounds_from(pts, n), yb)
    return trim(q)


def trim(q):
    cols = [i for i in range(len(q[0])) if any(r[i] for r in q)]
    return [r[cols[0]:cols[-1] + 1] for r in q]


# ---------------------------------------------------------------- icon

def icon_axis(f):
    """Mirror axis (in px) maximizing left/right agreement."""
    w = len(f[0])
    best = None
    for twice in range(w, 2 * w - w // 2):    # axis = twice / 2
        agree = 0.0
        for row in f:
            for x in range(w):
                m = twice - 1 - x
                if 0 <= m < w:
                    agree -= abs(row[x] - row[m])
                else:
                    agree -= row[x]
        if best is None or agree > best[0]:
            best = (agree, twice / 2)
    return best[1]


def label(f, thresh=0.5):
    """4-connected components of ink; antialias pixels join their neighbour."""
    h, w = len(f), len(f[0])
    lab = [[0] * w for _ in range(h)]
    n = 0
    for y in range(h):
        for x in range(w):
            if f[y][x] >= thresh and not lab[y][x]:
                n += 1
                stack = [(y, x)]
                lab[y][x] = n
                while stack:
                    cy, cx = stack.pop()
                    for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                        ny, nx = cy + dy, cx + dx
                        if 0 <= ny < h and 0 <= nx < w and not lab[ny][nx] and f[ny][nx] >= thresh:
                            lab[ny][nx] = n
                            stack.append((ny, nx))
    for y in range(h):                         # attach soft edge pixels
        for x in range(w):
            if not lab[y][x] and f[y][x] > 0.02:
                for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    ny, nx = y + dy, x + dx
                    if 0 <= ny < h and 0 <= nx < w and f[ny][nx] >= thresh:
                        lab[y][x] = lab[ny][nx]
                        break
    return lab, n


def grow(cm, base, target):
    """Area-preserving: thin strokes lose quadrants at a 0.5 threshold, so add
    the best-covered neighbours until the stroke's master area is restored."""
    q = set(base)
    if not q:
        best = max(cm, key=cm.get, default=None)
        if best is None or cm[best] < 0.15:
            return q
        q.add(best)
    while len(q) < target:
        cand = {}
        for (j, i) in q:
            for n in ((j + 1, i), (j - 1, i), (j, i + 1), (j, i - 1)):
                if n not in q and cm.get(n, 0) >= 0.2:
                    cand[n] = cm[n]
        if not cand:
            break
        q.add(max(sorted(cand), key=cand.get))
    return q


def parts_of(cells):
    cells, n = set(cells), 0
    while cells:
        n += 1
        stack = [cells.pop()]
        while stack:
            j, i = stack.pop()
            for nb in ((j + 1, i), (j - 1, i), (j, i + 1), (j, i - 1)):
                if nb in cells:
                    cells.remove(nb)
                    stack.append(nb)
    return n


def fit_icon(f, sx, sy, phy, nrows):
    """Symmetric icon, fitted stroke by stroke.

    The master icon is a segmented spine plus mirrored arc pairs whose 2-3 px
    strokes and gaps sit right at quadrant resolution. Sampled with one global
    phase they alias into spikes and fuse at the spine. Instead every master
    stroke (connected component) gets its own sub-quadrant phase and an
    area-preserving threshold, under one constraint: different strokes never
    touch, so every negative space of the master survives. Left-half strokes
    are fitted and mirrored; the axis sits mid-cell so the spine is one cell.
    """
    axis = icon_axis(f)
    w = len(f[0])
    m2 = int(2 * axis) - 1
    sym = [[(row[x] + (row[m2 - x] if 0 <= m2 - x < w else 0)) / 2 for x in range(w)] for row in f]
    lab, n = label(sym)
    half = int(axis / sx) + 2                  # quadrant columns left of the axis
    phx = half * sx - axis                     # axis -> quadrant boundary `half`
    comps = {}
    for y in range(len(sym)):
        for x in range(w):
            if lab[y][x]:
                comps.setdefault(lab[y][x], []).append((y, x))
    spine, left = [], []
    for c, pix in comps.items():
        xs = [p[1] for p in pix]
        if min(xs) < axis <= max(xs) + 1:
            spine.append(c)
        elif max(xs) < axis:
            left.append(c)
    area = {c: sum(sym[y][x] for y, x in comps[c]) for c in comps}
    longest = max(spine, key=lambda c: area[c])
    ly = [p[0] for p in comps[longest]]
    lmid = (min(ly) + max(ly)) / 2
    spine_rest = sorted((c for c in spine if c != longest),
                        key=lambda c: abs(sum(p[0] for p in comps[c]) / len(comps[c]) - lmid))
    order = [longest] + sorted(left, key=lambda c: -area[c]) + spine_rest

    owner = {}                                 # (qrow, qcol) -> component
    dropped = 0
    for c in order:
        pix = set(comps[c])
        field = [[sym[y][x] if (y, x) in pix else 0.0 for x in range(w)] for y in range(len(sym))]
        ys = [p[0] for p in pix]
        xs = [p[1] for p in pix]
        is_spine = c in spine
        target = max(1, round(area[c] / (sx * sy)))
        best = None
        dxs = [0] if is_spine else [k / 8 for k in range(-4, 5)]
        for dy in [k / 8 for k in range(-6, 7)]:
            for dx in dxs:
                px_, py_ = phx + dx * sx, phy + dy * sy
                j0 = max(0, int((min(ys) + py_) // sy) - 1)
                j1 = min(nrows - 1, int((max(ys) + 1 + py_) // sy) + 1)
                i0 = max(0, int((min(xs) + px_) // sx) - 1)
                i1 = int((max(xs) + 1 + px_) // sx) + 1
                cm = {}
                for j in range(j0, j1 + 1):
                    for i in range(i0, i1 + 1):
                        v = box(field, i * sx - px_, (i + 1) * sx - px_, j * sy - py_, (j + 1) * sy - py_)
                        if v > 0:
                            cm[(j, i)] = v
                cells = grow(cm, [k for k, v in cm.items() if v >= 0.5], target)
                if not cells:
                    continue
                if is_spine:                   # spine = exactly the centre cell, symmetric
                    cells = {(j, i) for j, i in cells if half - 1 <= i <= half}
                    cells |= {(j, 2 * half - 1 - i) for j, i in cells}
                elif any(i >= half - 1 for _, i in cells):
                    continue                   # would touch its own mirror image
                if not cells:
                    continue
                clash = any(owner.get(nb, c) != c
                            for (j, i) in cells
                            for nb in ((j, i), (j + 1, i), (j - 1, i), (j, i + 1), (j, i - 1)))
                if clash:
                    continue
                err = sum(abs(v - (1.0 if k in cells else 0.0)) for k, v in cm.items())
                score = (parts_of(cells) - 1, err + 0.5 * (abs(dx) + abs(dy)))
                if best is None or score < best[0]:
                    best = (score, cells)
        if best is None:
            dropped += 1                       # no room without fusing strokes
            continue
        for k in best[1]:
            owner[k] = c
    ncols = 2 * half
    q = [[0] * ncols for _ in range(nrows)]
    for (j, i), c in owner.items():
        if 0 <= j < nrows and 0 <= i < ncols:
            q[j][i] = 1
            if c not in spine:
                q[j][ncols - 1 - i] = 1        # mirror
    if half % 2 == 0:                          # axis boundary must be mid-cell (odd)
        q = [[0] + r for r in q]
    fit_icon.dropped = dropped
    return trim_symmetric(q)


def trim_symmetric(q):
    cols = [i for i in range(len(q[0])) if any(r[i] for r in q)]
    lo, hi = cols[0], cols[-1]
    n = len(q[0])
    m = min(lo, n - 1 - hi)
    if m % 2:                                  # keep the axis mid-cell after trimming
        m -= 1
    return [r[m:n - m] for r in q]


# ---------------------------------------------------------------- compose

# (min terminal columns, width budget in columns, canvas rows, wordmark height
#  in quadrant rows, allowed px-per-quadrant-row / px-per-quadrant-column).
# A phone cell is ~1:2, so ~2.0 is geometrically faithful to the master.
TIERS = (
    ("full", 50, 50, 8, 7, (1.85, 2.15)),
    ("compact", 44, 44, 8, 6, (1.80, 2.20)),
)


def compose(cov, cols, rows, word_q, aspect_range):
    """Icon + letters on a quadrant canvas at the smallest scale (= most
    detail) whose layout fits `cols` terminal columns."""
    elements = segment(cov)
    word = [e for e in elements if e[0] != "icon"]
    icon = elements[0]
    cols_of_word = range(word[0][1], word[-1][2] + 1)
    wy0 = min(y for y in range(len(cov)) if any(cov[y][x] >= 0.5 for x in cols_of_word))
    wy1 = max(y for y in range(len(cov)) if any(cov[y][x] >= 0.5 for x in cols_of_word)) + 1
    sy = (wy1 - wy0) / word_q
    for k in range(200):
        sx = 1.2 + k * 0.0125
        if not aspect_range[0] <= sy / sx <= aspect_range[1]:
            continue
        if len(cov[0]) / sx > 2 * cols + 8:    # cannot possibly fit
            continue
        canvas = layout(cov, icon, word, sx, sy, wy0, wy1, word_q, 2 * rows)
        if canvas and len(canvas[0]) <= 2 * cols:
            return canvas, {"sx": sx, "sy": sy, "aspect": sy / sx,
                            "dropped_spine_dashes": fit_icon.dropped}
    raise SystemExit(f"no layout fits {cols} columns")


def layout(cov, icon, word, sx, sy, wy0, wy1, word_q, nrows):
    """Vertical: the wordmark's bars are grid-fitted to quadrant rows; the
    icon shares the same (linear) mapping so both stay registered.
    Horizontal: icon, then letters, with the master's gaps (>= 1 quadrant)."""
    h = len(cov)
    top = round(wy0 / sy)                      # icon rows above the wordmark
    phy = top * sy - wy0
    if (h + phy) / sy > nrows + 0.5 or phy < -sy * 0.5:
        return None
    parts = [fit_icon(element_field(cov, icon[1], icon[2], close_seams=False),
                      sx, sy, phy, nrows)]
    letters = [element_field(cov, a, b, close_seams=True) for _, a, b in word]
    ystr = [0] * (h + 1)
    for ln in letters:
        for b, s in enumerate(edge_strength(ln, "y")):
            ystr[b] += s
    inner = bounds_from(snap_edges(ystr, wy0, wy1, word_q, min_feature=3, rel=0.15), word_q)
    yb = ([inner[0] - (top - j) * sy for j in range(top)] + inner +
          [inner[-1] + (j + 1) * sy for j in range(nrows - top - word_q)])
    gaps, prev_end = [], icon[2]
    for (_, a, b), fl in zip(word, letters):
        gaps.append(max(1, round((a - prev_end - 1) / sx)))
        parts.append(fit_letter(fl, sx, yb))
        prev_end = b
    canvas = [[] for _ in range(nrows)]
    for k, part in enumerate(parts):
        for y in range(nrows):
            if k:
                canvas[y].extend([0] * gaps[k - 1])
            canvas[y].extend(part[y])
    return canvas


# ---------------------------------------------------------------- 5. emit

def to_lines(canvas):
    """Quadrant canvas -> glyph lines, trimmed to the ink bounding box."""
    if len(canvas[0]) % 2:
        canvas = [r + [0] for r in canvas]
    if len(canvas) % 2:
        canvas = canvas + [[0] * len(canvas[0])]
    lines = []
    for j in range(0, len(canvas), 2):
        s = []
        for i in range(0, len(canvas[0]), 2):
            bits = (canvas[j][i] | canvas[j][i + 1] << 1 |
                    canvas[j + 1][i] << 2 | canvas[j + 1][i + 1] << 3)
            s.append(GLYPH[DIAGONAL[bits][0]] if bits in DIAGONAL else GLYPH[bits])
        lines.append("".join(s))
    while lines and not lines[-1].strip():
        lines.pop()
    while lines and not lines[0].strip():
        lines.pop(0)
    lead = min(len(ln) - len(ln.lstrip()) for ln in lines if ln.strip())
    return [ln[lead:].rstrip() for ln in lines]


def to_ans(lines):
    """Ink-only truecolor: fg SGR around each glyph run, reset closes every
    run, background never touched (transparent)."""
    on = "\x1b[38;2;%d;%d;%dm" % LIME
    return "".join(re.sub(r"(\S+)", lambda m: on + m.group(1) + "\x1b[0m", ln) + "\n"
                   for ln in lines)


def icon_symmetric(canvas):
    ink = [any(r[i] for r in canvas) for i in range(len(canvas[0]))]
    a = ink.index(True)
    b = next(i for i in range(a, len(ink) - 1) if not ink[i] and not ink[i + 1])
    return all(r[a:b] == r[a:b][::-1] for r in canvas)


def verify(name, lines, data, budget, canvas):
    fails = []
    width, height = max(len(ln) for ln in lines), len(lines)
    if width > budget:
        fails.append(f"width {width} > {budget}")
    if set("".join(lines)) - set(GLYPH.values()):
        fails.append(f"unexpected glyphs {set(''.join(lines)) - set(GLYPH.values())}")
    seqs = re.findall(r"\x1b\[([0-9;]*)([@-~])", data)
    if {f for _, f in seqs} - {"m"}:
        fails.append("non-SGR escape (cursor motion?)")
    if any(p.startswith("48") or ";48;" in p for p, _ in seqs):
        fails.append("background colour escape")
    if any(ln and not ln.endswith("\x1b[0m") for ln in data.split("\n")):
        fails.append("line without trailing reset")
    if not icon_symmetric(canvas):
        fails.append("icon not mirror-symmetric")
    print(f"  [{'PASS' if not fails else 'FAIL'}] {name}: {width}x{height}, "
          f"{len(data.encode())} bytes")
    for f in fails:
        print(f"         !! {f}")
    return not fails


def build_all(out_dir=HERE, quiet=False):
    cov = load_coverage()
    results, ok = [], True
    for name, min_cols, budget, rows, word_q, aspect in TIERS:
        canvas, meta = compose(cov, budget, rows, word_q, aspect)
        lines = to_lines(canvas)
        data = to_ans(lines)
        with open(os.path.join(out_dir, f"tendril_{name}.ans"), "w") as f:
            f.write(data)
        if not quiet:
            ok &= verify(f"tendril_{name}.ans", lines, data, budget, canvas)
            print(f"         scale {meta['sx']:.4f} x {meta['sy']:.4f} px/quadrant "
                  f"(aspect {meta['aspect']:.2f}), spine dashes merged: "
                  f"{meta['dropped_spine_dashes']}")
            for ln in lines:
                print("         |" + ln.ljust(max(map(len, lines))) + "|")
        results.append((name, min_cols, lines))
    return results, ok


def embed_block(results):
    out = ["_MASTHEAD = (",
           "    # (min columns, lines) - generated by assets/masthead/build_masthead.py --embed"]
    for name, min_cols, lines in results:
        out.append(f"    ({min_cols}, (  # {name}")
        out += [f'        "{ln}",' for ln in lines]
        out.append("    )),")
    out.append(")")
    return "\n".join(out)


if __name__ == "__main__":
    if "--extract" in sys.argv:
        args = [a for a in sys.argv[1:] if not a.startswith("--")]
        extract(args[0] if args else DEFAULT_MASTER)
        sys.exit(0)
    results, ok = build_all()
    if "--embed" in sys.argv and ok:
        print()
        print(embed_block(results))
    sys.exit(0 if ok else 1)
